paths:
  /FITple/auth/find-id:
    post:
      tags:
        - Find-id
      summary: 아이디 찾기
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 유저 이메일
                  example: swaggerTest@naver.com
                nickname:
                  type: string
                  description: 유저 닉네임
                  example: test
              required:
                - email
                - nickname
      responses:
        '200':
          description: 아이디 찾기 성공!
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      user_id:
                        type: string
                        description: 유저 아이디
                        example: swaggerTest
                      email:
                        type: string
                        description: 유저 이메일
                        example: swaggerTest@naver.com
                      nickname:
                        type: string
                        description: 유저 닉네임
                        example: test
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        '401':
          description: 비어있는 데이터
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: FINDID002
              message:
                type: string
                example: 데이터가 비어있습니다.
        '402':
          description: 존재하지 않는 사용자
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: FINDID002
              message:
                type: string
                example: 존재하지 않는 사용자입니다.
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.