paths:
  /FITple/logout:
    post:
      tags:
        - Logout
      summary: 로그아웃

      responses:
        '200':
          description: 로그아웃 성공!
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: "success!"
              result:
                properties:
                  accessToken:
                    type: string
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.