paths:
  /FITple/myprofile:
    post:
      tags:
        - Myprofile
      summary: 마이프로필 저장
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: 사용자 이미지
                data:
                  type: string
                  description: JSON 형식의 사용자 정보 및 체형 정보
                  example: '{"userInfo": {"nickname": "testUser", "gender": "male", "one_line_info": "test", "perfer_fit": ["fit1", "fit2"], "perfer_style": ["style1", "style2"]}, "bodyInfo": {"height": 180, "weight": 70, "shoulder_width": 45, "chest_circumference": 100, "arm_length": 60, "waist_circumference": 85, "thigh_circumference": 55, "hip_circumference": 95}}'
              required:
                - image
                - data
      responses:
        '200':
          description: 마이프로필 저장 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
        '401':
          description: 사용자 이미지가 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE001
                  message:
                    type: string
                    example: "사용자 이미지가 존재하지 않습니다."
        '402':
          description: 기본 정보 또는 체형 정보 데이터가 비어 있음
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE002
                  message:
                    type: string
                    example: "기본 정보 또는 체형 정보 데이터가 없습니다."
        '403':
          description: 체형 정보 데이터가 이미 존재함
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE003
                  message:
                    type: string
                    example: "체형 정보 데이터가 존재합니다."
        '404':
          description: 체형 정보 데이터 저장 중 오류 발생
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE004
                  message:
                    type: string
                    example: "체형 정보 데이터 저장 중 오류가 발생했습니다."
        '405':
          description: 기본 정보 데이터 저장 중 오류 발생
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE005
                  message:
                    type: string
                    example: "기본 정보 데이터 저장 중 오류가 발생했습니다."
        '406':
          description: 사용자 이미지 데이터 저장 중 오류 발생
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE006
                  message:
                    type: string
                    example: "사용자 이미지 데이터 저장 중 오류가 발생했습니다."
        '407':
          description: 사용자 닉네임 중복 오류 발생
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: MYPROFILE007
                  message:
                    type: string
                    example: "이미 사용중인 닉네임입니다."
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."
