paths:
  /FITple/auth/reset-password:
    post:
      tags:
        - Reset-Password
      summary: 비밀번호 변경 권한 확인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: 유저 아이디
                  example: swaggerTest
                email:
                  type: string
                  description: 유저 이메일
                  example: swaggerTest@naver.com
                nickname:
                  type: string
                  description: 유저 닉네임
                  example: test
              required:
                - user_id
                - email
                - nickname
      responses:
        '200':
          description: 비밀번호 변경 권한 확인 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        '401':
          description: 비어있는 데이터
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: AUTHRESETPASSWORD001
                  message:
                    type: string
                    example: 데이터가 비어있습니다.
        '402':
          description: 존재하지 않는 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: AUTHRESETPASSWORD002
                  message:
                    type: string
                    example: 존재하지 않는 사용자입니다.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.

    patch:
      tags:
        - Reset-Password
      summary: 비밀번호 변경
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  description: 변경할 비밀번호
                  example: 7654321
              required:
                - newPassword
      responses:
        '200':
          description: 비밀번호 변경 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        '401':
          description: 비밀번호 변경 권한 토큰 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: SETRESETPASSWORD001
                  message:
                    type: string
                    example: 비밀번호 변경 권한 토큰이 존재하지 않습니다.
        '402':
          description: 변경할 비밀번호 데이터 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: SETRESETPASSWORD002
                  message:
                    type: string
                    example: 변경할 비밀번호 데이터가 존재하지 않습니다.
        '403':
          description: 비밀번호 변경에 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: SETRESETPASSWORD003
                  message:
                    type: string
                    example: 비밀번호 변경에 실패했습니다.
        '406':
          description: 유효하지 않은 비밀번호 변경 권한 토큰
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: SETRESETPASSWORD004
                  message:
                    type: string
                    example: 비밀번호 변경 권한 토큰이 유효하지 않습니다.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
