paths:
  /FITple/search/main:
    get:
      tags:
        - Search
      summary: 전체 옷장 조회 로직
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 검색 메인화면 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "clothData": [
                    {
                      "cloth_id": 21,
                      "nickname": "testUser",
                      "brand": "아디다스",
                      "cloth_name": "에센셜 풀업 후디",
                      "size": "S",
                      "fit": "레귤러"
                    },
                    {
                      "cloth_id": 20,
                      "nickname": "testUser",
                      "brand": "아디다스",
                      "cloth_name": "에센셜 풀업 후디",
                      "size": "S",
                      "fit": "레귤러"
                    }
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /FITple/search/{clothId}:
    get:
      tags:
        - Search
      summary: 옷 상세 조회 로직
      parameters:
        - name: clothId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 옷 상세 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "clothData": [
                    {
                      "brand": "아디다스",
                      "cloth_name": "에센셜 풀업 후디",
                      "product_code": "IL2516",
                      "size": "M",
                      "fit": "세미오버",
                      "color": "그레이",
                      "URL": "https://adidas.co.kr/1245",
                      "memo": "길이는 딱 맞고, 팔이 조금 길다."
                    }
                  ],
                  "userData": [
                    {
                      "nickname": "닉네임1",
                      "height": "161",
                      "weight": "51"
                    }
                  ],
                  "prefer_fit": [
                    "슬림",
                    "레귤러"
                  ],
                  "prefer_style": [
                    "러블리",
                    "모던시크"
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /FITple/search:
    get:
      tags:
        - Search
      summary: 통합 검색 조회 로직
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: category
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 통합 검색 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                      "clothData": [
                        {
                          "nickname": "닉네임1",
                          "brand": "아디다스",
                          "cloth_name": "아디다스 에센셜 후디",
                          "size": "XS",
                          "fit": "레귤러"
                        },
                        {
                          "nickname": "닉네임2",
                          "brand": "아디다스",
                          "cloth_name": "아디다스 에센셜 후디",
                          "size": "XS",
                          "fit": "레귤러"
                        }
                      ],
                      "brandData": [
                        {
                          "brand_id": 2,
                          "brand_name": "아디다스",
                          "eng_name": "ADIDAS"
                        }
                      ],
                      "userData": [
                        "해당 유저는 등록되어 있지 않아요."
                      ]
                    }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /FITple/search/brand/{brandId}:
    get:
      tags:
        - Search
      summary: 브랜드 상세 조회 로직
      parameters:
        - name: brandId
          in: path
          required: true
          schema:
            type: integer
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: category
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 브랜드 상세 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "brand_name": "아디다스",
                  "eng_name": "ADIDAS",
                  "clothData": [
                    {
                      "nickname": "닉네임1",
                      "brand": "아디다스",
                      "cloth_name": "에센셜 풀업 후디",
                      "size": "M",
                      "fit": "세미오버"
                    },
                    {
                      "nickname": "닉네임1",
                      "brand": "아디다스",
                      "cloth_name": "아디다스 에센셜 후디",
                      "size": "XS",
                      "fit": "레귤러"
                    }
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.